<a href="https://colab.research.google.com/github/bbwolcott/nyu-python-public-policy/blob/master/HW1_Wolcott.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [41]:
df = pd.read_csv('/content/drive/My Drive/Graduate School/Fall 2019/Python/Data for Python/311_Service_Requests_2018-19.csv', header='infer')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (8,17,20,31,34) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [42]:
df.count()

Unique Key                        2859200
Created Date                      2859200
Closed Date                       2722927
Agency                            2859200
Agency Name                       2859200
Complaint Type                    2859200
Descriptor                        2816522
Location Type                     2242215
Incident Zip                      2746912
Incident Address                  2483931
Street Name                       2483750
Cross Street 1                    1719330
Cross Street 2                    1712706
Intersection Street 1              613896
Intersection Street 2              611987
Address Type                      2579813
City                              2725223
Landmark                           185198
Facility Type                      769320
Status                            2859200
Due Date                           978779
Resolution Description            2615253
Resolution Action Updated Date    2795696
Community Board                   2859200
BBL                               2329340
Borough                           2859200
X Coordinate (State Plane)        2691466
Y Coordinate (State Plane)        2691466
Open Data Channel Type            2859200
Park Facility Name                2859011
Park Borough                      2859200
Vehicle Type                          252
Taxi Company Borough                 2248
Taxi Pick Up Location               25748
Bridge Highway Name                  3872
Bridge Highway Direction             4294
Road Ramp                            4270
Bridge Highway Segment               5878
Latitude                          2691466
Longitude                         2691466
Location                          2691466
dtype: int64

In [43]:
df[['Created Date']].min()

Created Date    01/01/2019 01:00:00 PM
dtype: object

In [44]:
df[['Created Date']].max()

Created Date    12/31/2018 12:59:41 PM
dtype: object

In [45]:
print(type('Created Date'))

<class 'str'>

In [46]:
df.head()

   Unique Key  ...                                 Location
0    39888071  ...   (40.79333937834769, -73.9429417746998)
1    39889166  ...   (40.82012422332215, -73.9530712339799)
2    39882869  ...   (40.67080917938279, -73.9513990916184)
3    39894246  ...  (40.74026158873342, -73.99051651686905)
4    39881329  ...  (40.68814402968042, -73.75098958473612)

[5 rows x 41 columns]

In [47]:
df.tail()

         Unique Key  ...                                 Location
2859195    43619262  ...   (40.87970084316435, -73.9010571445122)
2859196    43622052  ...  (40.70178323733244, -73.92055493919345)
2859197    43625918  ...   (40.66999185896368, -73.9224889475533)
2859198    43622055  ...                                      NaN
2859199    43623704  ...  (40.63679359185655, -74.15397942810047)

[5 rows x 41 columns]

The min and max results are surprising because the min date is a later date than the max date. This is likely due to the data type. Created date is currently stored as a string, and while 2019 is later than 2018, the 2018 date is a larger because it starts in December (12) instaed of January (01). The true created date min is 8/1/18, adn the true careate date max is 8/24/2019.

What are the best way to debug error messages? What functions and methods are in the pandas and numpy libraries?